version: 2.1
orbs:
  shared: getoutreach/shared@1.56.0

# DEPRECATED: Use the devbase orb instead:
# https://github.com/getoutreach/devbase/tree/main/orbs/shared
commands:
  with_job_span:
    parameters:
      steps:
        type: steps
    steps:
      - run:
          name: DEPRECATION NOTICE
          command: echo "with_job_span is deprecated and should be removed"
      - steps: << parameters.steps >>
      
jobs:
  build_push_docker_image:
    executor:
      name: shared/testbed-machine
    resource_class: xlarge
    steps:
      - shared/setup_environment:
          machine: true
      - shared/build_docker_image
      - store_artifacts:
          path: /tmp/test-results/image_scan.json
